/**
 * Writes web/abi.js from the compiled artifacts, so the site's ABI can never
 * drift from the deployed contract. Runs automatically on `npm run web` and
 * `npm run deploy:local`; run it by hand with `npm run abi`.
 */
const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const OUT = path.join(ROOT, "web", "abi.js");

function artifactAbi(contract, file) {
  const p = path.join(ROOT, "artifacts", "contracts", file, `${contract}.json`);
  if (!fs.existsSync(p)) {
    throw new Error(`Missing artifact for ${contract}. Run \`npm run compile\` first.`);
  }
  return JSON.parse(fs.readFileSync(p, "utf8")).abi;
}

/**
 * Superset ABI for the NFT side. the collection will not implement every owner-listing
 * method here — the frontend probes them in order and uses whichever answers.
 */
const NFT_ABI = [
  "function name() view returns (string)",
  "function symbol() view returns (string)",
  "function ownerOf(uint256) view returns (address)",
  "function tokenURI(uint256) view returns (string)",
  "function balanceOf(address) view returns (uint256)",
  "function isApprovedForAll(address owner, address operator) view returns (bool)",
  "function setApprovalForAll(address operator, bool approved)",
  "function getApproved(uint256) view returns (address)",
  "function approve(address to, uint256 tokenId)",
  "function transferFrom(address from, address to, uint256 idOrAmount)",
  // --- owner enumeration, probed in this order ---
  "function owned(address) view returns (uint256[])",
  "function ownedIds(address) view returns (uint256[])",
  "function tokensOfOwner(address) view returns (uint256[])",
  "function erc721BalanceOf(address) view returns (uint256)",
  "function tokenOfOwnerByIndex(address owner, uint256 index) view returns (uint256)",
  // --- ERC-404 exemption flags (read-only; informational in the UI) ---
  "function erc721TransferExempt(address) view returns (bool)",
  "function whitelist(address) view returns (bool)",
  "event Transfer(address indexed from, address indexed to, uint256 indexed idOrAmount)",
];

const ERC20_ABI = [
  "function name() view returns (string)",
  "function symbol() view returns (string)",
  "function decimals() view returns (uint8)",
  "function totalSupply() view returns (uint256)",
  "function balanceOf(address) view returns (uint256)",
  "function allowance(address owner, address spender) view returns (uint256)",
  "function approve(address spender, uint256 amount) returns (bool)",
  "function transfer(address to, uint256 amount) returns (bool)",
];

function writeAbi() {
  const bundle = {
    farm: artifactAbi("NftStakeFarm", "NftStakeFarm.sol"),
    nft: NFT_ABI,
    erc20: ERC20_ABI,
  };

  const body =
    "// AUTO-GENERATED by scripts/export-abi.js — do not edit by hand.\n" +
    `window.FARM_ABI = ${JSON.stringify(bundle, null, 2)};\n`;

  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, body);
  return { file: OUT, entries: bundle.farm.length };
}

module.exports = { writeAbi };

if (require.main === module) {
  const { file, entries } = writeAbi();
  console.log(`Wrote ${path.relative(ROOT, file)} (farm ABI: ${entries} entries)`);
}
